### ISSUE TITLE
Where can I find the what the codes in the gini Excel file mean?

### ISSUE THREAD

**Issue by mmerrittsmith** [WIDworld/wid-world#2]
I'm working on a project and I already have a ton of wealth Gini coefficients from Credit Suisse, but I'd like to include more historical data if possible. In order to do that, I'd like to know what the values in the "component" column correspond to in wid-world/data-input.  I've also included the file here for simplicity. 

Thanks guys.

-Merritt

[gini.xlsx](https://github.com/WIDworld/wid-world/files/1805641/gini.xlsx)

**Comment by thomasblanchet** [comment]
You can search in table: http://wid.world/summary-table/ to get the info. Alternatively the meaning of the codes is explained in the documentation of the Stata or R packages.
